# Generated by Django 5.2.7 on 2025-10-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentifications', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
