# Generated by Django 5.2.7 on 2025-10-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentifications', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
