# Generated by Django 5.2.7 on 2025-10-08 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('0.5', 'TERRIBLE'), ('1', 'AWFUL'), ('1.5', 'VERY POOR'), ('2', 'POOR'), ('2.5', 'BELOW AVERAGE'), ('3', 'AVERAGE'), ('3.5', 'DECENT'), ('4', 'GOOD'), ('4.5', 'VERY GOOD'), ('5', 'EXCELENT')], default='3', max_length=50)),
                ('feed_back', models.TextField()),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
