# Generated by Django 5.2.7 on 2025-10-08 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_seats', models.IntegerField()),
                ('is_active', models.CharField(choices=[('active', 'ACTIVE'), ('unactive', 'UNACTIVE')], default='active', max_length=100)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trips.trip')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
