# Generated by Django 5.2.7 on 2025-10-08 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('from_where', models.CharField(max_length=250)),
                ('to_where', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seats', models.IntegerField(default=4)),
                ('price', models.IntegerField()),
                ('available', models.CharField(choices=[('available', 'AVAILABLE'), ('unavailable', 'UNAVAILABLE')], default='available', max_length=60)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
